---
- name: Sample playbook
  hosts: all
  gather_facts: no
  ignore_errors: yes
  tasks:
  - name: Welcome message
    debug:
      msg: "{{ lookup('env', 'TOWER_INSTANCE') }} and {{ lookup('env', 'TOWER_USERNAME') }} and {{ lookup('env', 'TOWER_PASSWORD') }}"
...
