---
- name: Sample playbook
  hosts: all
  gather_facts: no
  ignore_errors: yes
  tasks:
  - name: Welcome message
    debug:
      msg: "Server name is {{ inventory_hostname }}"
      
  - name: Create hello.txt
    file:
      path: /tmp/hello.txt
      state: touch
...
